os: 
  - osx
  - linux

language: sh
php:
  - 5.6

script: uname -a

matrix:
  include:
    - os: osx
      php: "5.6"
      language: generic
      before_install:
        - brew update && brew tap homebrew/php && brew install php56

install:
  - cd imagick-3.4.3
  - phpize
  - ./configure
  - make
  - make install
script:
  - export NO_INTERACTION=1
  - export REPORT_EXIT_STATUS=1
  - export TEST_PHP_ARGS="--show-diff"
  - make test        