os: 
  - osx

language: sh
php: 5.6

script: uname -a

before_install:
        - brew install imagemagick
        - curl -s https://php-osx.liip.ch/install.sh | bash -s 5.6

install:
  - cd imagick-3.4.3
  - phpize
  - export CFLAGS="-arch i386 -g -Os -pipe -no-cpp-precomp"
  - export CCFLAGS="-arch i386 -g -Os -pipe"
  - export CXXFLAGS="-arch i386 -g -Os -pipe"
  - export LDFLAGS="-arch i386 -bind_at_load"
  - ./configure
  - make
  - cd ..
  - mkdir git-stage
  - cp imagick-3.4.3/modules/imagick.so git-stage/
  - ./push.sh