os: 
  - osx

language: php
php: 5.6

script: uname -a

before_install:
        - brew update && brew tap homebrew/php && brew install imagemagick

install:
  - cd imagick-3.4.3
  - phpize
  - export CFLAGS="-arch i386"
  - export LDFLAGS="-arch i386"
  - ./configure
  - make
  - make install
script:
  - export NO_INTERACTION=1
  - export REPORT_EXIT_STATUS=1
  - export TEST_PHP_ARGS="--show-diff"
  - make test        