os: 
  - osx

language: sh
php: 5.6

script: uname -a

before_install:
        - brew install imagemagick
        - curl -s https://php-osx.liip.ch/install.sh | bash -s 5.6

install:
  - cd imagick-3.4.3
  - phpize
  - export CFLAGS="-arch i386"
  - export LDFLAGS="-arch i386"
  - ./configure
  - make
  - cd ..
  - mkdir git-stage
  - cp imagick-3.4.3/modules/imagick.so git-stage/
  - ls git-stage
  - ./push.sh