os: 
  - osx

language: sh
php: 5.6

script: uname -a

before_install:
        - brew update && brew install imagemagick
        - curl -s https://php-osx.liip.ch/install.sh | bash -s 5.6

install:
  - cd imagick-3.4.3
  - phpize
  - export CFLAGS="-arch i386"
  - export LDFLAGS="-arch i386"
  - ./configure
  - make

after_success:
  - mkdir build
  - cp imagick-3.4.3/modules/imagick.so build/
  - ./push.sh
env:
  global:
    secure: 25b638e7c94c5f815ce2b441a74810ac047391f6